### Classify Business Type

Classify each business as either a restaurant, cafe, school, or other. A restaurant should have the word 'restaurant' in the business name. For cafes, either 'cafe', 'caf√©', or 'coffee' can be in the business name. 'School' should be in the business name for schools. All other businesses should be classified as 'other'. Output the business name and the calculated classification.

In [25]:
# Import your libraries
import pandas as pd

In [26]:
# set display options
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80

In [27]:
#sf_restaurant_health_violations = pd.read_clipboard()
#sf_restaurant_health_violations.to_csv('sf_restaurant_health_violations.csv',index=False)
sf_restaurant_health_violations = pd.read_csv('sf_restaurant_health_violations.csv')
sf_restaurant_health_violations.head()

,business_id,business_name,business_address,business_city,business_state,business_postal_code,business_latitude,business_longitude,business_location,business_phone_number,inspection_id,inspection_date,inspection_score,inspection_type,violation_id,violation_description,risk_category
0,5800,John Chin Elementary School,350 Broadway St,San Francisco,CA,94133.0,37.798,-122.403,"{'longitude': '-122.403154', 'needs_recoding': False, 'latitude': '37.798358...",NaN,5800_20171017,2017-10-17 00:00:00,98.0,Routine - Unscheduled,5800_20171017_103149,Wiping cloths not clean or properly stored or inadequate sanitizer,Low Risk
1,64236,Sutter Pub and Restaurant,700 Sutter St,San Francisco,CA,94102.0,37.789,-122.412,"{'longitude': '-122.41188', 'needs_recoding': False, 'latitude': '37.78881',...",NaN,64236_20170725,2017-07-25 00:00:00,88.0,Routine - Unscheduled,64236_20170725_103133,Foods not protected from contamination,Moderate Risk
2,1991,SRI THAI CUISINE,4621 LINCOLN Way,San Francisco,CA,94122.0,37.764,-122.508,"{'longitude': '-122.507779', 'needs_recoding': False, 'latitude': '37.764073...",NaN,1991_20171129,2017-11-29 00:00:00,86.0,Routine - Unscheduled,1991_20171129_103139,Improper food storage,Low Risk
3,3816,Washington Bakery & Restaurant,733 Washington St,San Francisco,CA,94108.0,37.795,-122.406,"{'longitude': '-122.405845', 'needs_recoding': False, 'latitude': '37.795174...",NaN,3816_20160728,2016-07-28 00:00:00,67.0,Routine - Unscheduled,3816_20160728_103108,Contaminated or adulterated food,High Risk
4,39119,Brothers Restaurant,4128 GEARY Blvd,San Francisco,CA,94118.0,37.781,-122.464,"{'longitude': '-122.463762', 'needs_recoding': False, 'latitude': '37.781148...",NaN,39119_20160718,2016-07-18 00:00:00,79.0,Routine - Unscheduled,39119_20160718_103133,Foods not protected from contamination,Moderate Risk

In [28]:
# Create new business type column with default 'z'
sf_restaurant_health_violations['business_type'] = 'z'

In [29]:
# create df of only restaurants
restaurants = sf_restaurant_health_violations.loc[sf_restaurant_health_violations['business_name'].str.contains("restaurant", na=False, case=False)]
restaurants.head()

,business_id,business_name,business_address,business_city,business_state,business_postal_code,business_latitude,business_longitude,business_location,business_phone_number,inspection_id,inspection_date,inspection_score,inspection_type,violation_id,violation_description,risk_category,business_type
1,64236,Sutter Pub and Restaurant,700 Sutter St,San Francisco,CA,94102.0,37.789,-122.412,"{'longitude': '-122.41188', 'needs_recoding': False, 'latitude': '37.78881',...",NaN,64236_20170725,2017-07-25 00:00:00,88.0,Routine - Unscheduled,64236_20170725_103133,Foods not protected from contamination,Moderate Risk,z
3,3816,Washington Bakery & Restaurant,733 Washington St,San Francisco,CA,94108.0,37.795,-122.406,"{'longitude': '-122.405845', 'needs_recoding': False, 'latitude': '37.795174...",NaN,3816_20160728,2016-07-28 00:00:00,67.0,Routine - Unscheduled,3816_20160728_103108,Contaminated or adulterated food,High Risk,z
4,39119,Brothers Restaurant,4128 GEARY Blvd,San Francisco,CA,94118.0,37.781,-122.464,"{'longitude': '-122.463762', 'needs_recoding': False, 'latitude': '37.781148...",NaN,39119_20160718,2016-07-18 00:00:00,79.0,Routine - Unscheduled,39119_20160718_103133,Foods not protected from contamination,Moderate Risk,z
8,68872,Jiang Ling Cuisine Restaurant,2517 SAN BRUNO Ave,San Francisco,CA,94134.0,37.730,-122.405,"{'longitude': '-122.404526', 'needs_recoding': False, 'latitude': '37.729985...",NaN,68872_20171212,2017-12-12 00:00:00,72.0,Routine - Unscheduled,68872_20171212_103105,Improper cooling methods,High Risk,z
9,80242,Wing Lee BBQ Restaurant,501 Clement St.,San Francisco,CA,94118.0,NaN,NaN,NaN,NaN,80242_20160509,2016-05-09 00:00:00,78.0,Routine - Unscheduled,80242_20160509_103149,Wiping cloths not clean or properly stored or inadequate sanitizer,Low Risk,z

In [30]:
# create df of only cafes
cafe = sf_restaurant_health_violations.loc[sf_restaurant_health_violations['business_name'].str.contains("cafe", na=False, case=False)]
caf√© = sf_restaurant_health_violations.loc[sf_restaurant_health_violations['business_name'].str.contains("caf√©", na=False, case=False)]
coffee = sf_restaurant_health_violations.loc[sf_restaurant_health_violations['business_name'].str.contains("coffee", na=False, case=False)]
cafes = pd.concat([cafe, caf√©, coffee], axis=0)

In [31]:
cafes.head()

,business_id,business_name,business_address,business_city,business_state,business_postal_code,business_latitude,business_longitude,business_location,business_phone_number,inspection_id,inspection_date,inspection_score,inspection_type,violation_id,violation_description,risk_category,business_type
16,509,Cafe Bakery,1365 Noriega St,San Francisco,CA,94122.0,37.754,-122.478,"{'longitude': '-122.478248', 'needs_recoding': False, 'latitude': '37.75409'...",NaN,509_20160328,2016-03-28 00:00:00,NaN,Reinspection/Followup,NaN,NaN,NaN,z
22,4421,Crepe Cafe,Pier 39 Space D-3,San Francisco,CA,94133.0,37.808,-122.410,"{'longitude': '-122.410189', 'needs_recoding': False, 'latitude': '37.80824'...",NaN,4421_20180326,2018-03-26 00:00:00,86.0,Routine - Unscheduled,4421_20180326_103144,Unapproved or unmaintained equipment or utensils,Low Risk,z
24,86990,Allstars Cafe Inc,1500 Market St,San Francisco,CA,94102.0,NaN,NaN,NaN,1.415526e+10,86990_20170829,2017-08-29 00:00:00,83.0,Routine - Unscheduled,86990_20170829_103119,Inadequate and inaccessible handwashing facilities,Moderate Risk,z
41,36473,Maggie Cafe,848 Grant Ave,San Francisco,CA,94108.0,37.795,-122.406,"{'longitude': '-122.406356', 'needs_recoding': False, 'latitude': '37.794898...",NaN,36473_20151202,2015-12-02 00:00:00,88.0,Routine - Unscheduled,36473_20151202_103119,Inadequate and inaccessible handwashing facilities,Moderate Risk,z
51,81886,Cafe Broadway,674 Broadway St,San Francisco,CA,94133.0,NaN,NaN,NaN,NaN,81886_20180418,2018-04-18 00:00:00,76.0,Routine - Unscheduled,81886_20180418_103144,Unapproved or unmaintained equipment or utensils,Low Risk,z

In [32]:
# Create dataframe of only schools
school = sf_restaurant_health_violations.loc[sf_restaurant_health_violations['business_name'].str.contains("school", na=False, case=False)]

In [33]:
# create business type columns for each df
restaurants['business_type'] = 'restaurant'
cafes['business_type'] = 'cafe'
school['business_type'] = 'school'

<ipython-input-33-55a7752181aa>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurants['business_type'] = 'restaurant'
<ipython-input-33-55a7752181aa>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  school['business_type'] = 'school'

In [34]:
# concat all dataframes
final = pd.concat([sf_restaurant_health_violations, restaurants, cafes,school], axis=0)

In [35]:
# sort by business name the business type
final.sort_values(by=['business_name', 'business_type'], ascending=[True, True],inplace=True)

In [36]:
# drop duplicates on business name, this will drop any of the 'z' business tpyes if they are present witha  different value
final = final.drop_duplicates(subset=['business_name'])

In [37]:
# Rename business tpye 'z' to 'other'
final['business_type'] = final['business_type'].replace({'z': 'Other'})

In [38]:
# get only the columns requested
final[['business_name','business_type']]

                                      business_name business_type
266                      24 Hour Fitness Club, #273         Other
263                          24th and Folsom Eatery         Other
249                     7-Eleven, Store 2366-21389F         Other
98                    95117 Premium Commissary Room         Other
163                                      A La Turca         Other
..                                              ...           ...
9                           Wing Lee BBQ Restaurant    restaurant
132                                   Wing Lum Cafe          cafe
52                                YUMMA'S MED GRILL         Other
243  Yerba Buena Tea Co (formerly Tea Smiths of SF)         Other
106                                    Yummy Sticks         Other

[266 rows x 2 columns]